openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact book API
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    APi for contact book
tags:
  - name: Contacts
    description: API for contacts
servers:
  - url: http://localhost:8080
  # - url: посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    $ref: '../swagger/paths/contacts/{id}/get.yaml'
  /contacts:
    $ref: '../swagger/paths/contacts/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
